; ============================================================================
;  PlatformIO Project Configuration - HEELPMEE Firmware v1.3.0
;  Board : LilyGo T-SIM7670G-S3
; ============================================================================

[env:lilygo-sim7670g-s3]

platform  = espressif32@6.12.0
board     = esp32s3box
framework = arduino

board_build.partitions           = default_8MB.csv
board_build.filesystem           = littlefs

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DFIRMWARE_VERSION=\"1.3.0\"
    -DEIDSP_QUANTIZE_FILTERBANK=0
    -DEI_CLASSIFIER_SLICES_PER_MODEL_WINDOW=4
    -DEIDSP_LOAD_CMSIS_DSP_SOURCES=0
    -DEI_PORTING_ARDUINO=1
    -DEI_CLASSIFIER_TFLITE_LOAD_CMSIS_NN_SOURCES=0

upload_speed                     = 921600
monitor_speed                    = 115200
monitor_filters                  = time, default, esp32_exception_decoder

lib_deps =
    mikalhart/TinyGPSPlus
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit NeoPixel
    links2004/WebSockets@^2.4.1

lib_extra_dirs = lib

lib_ignore =
build_unflags = -DEIDSP_LOAD_CMSIS_DSP_SOURCES=1
